### ISSUE TITLE
Invalid URL or File Path error

### ISSUE THREAD

**Issue by shpyntov** [marcussacana/DirectPackageInstaller#9] opened 2022-01-16 21:05 UTC
I have pkg link http://192.168.1.80/It%20Takes%20Two%20[5.05%20Fix]/EP0006-CUSA16746_00-NUTSEU0000000000-A0100-V0102.pkg

Link is correct and I can download file by following this link.

But after click on "load" button i have this error:

![изображение](https://user-images.githubusercontent.com/15773091/149677944-f809a83c-525b-4598-b0dd-36c83eaef454.png)

**Comment by marcussacana** [comment] 2022-01-16 22:32
Self hosted? if its a pkg in the same machine you can just put the file path instead the link and will works.
Anyway, still a bug because of the [ ] in the url, usually that should be escaped... I can't just replace because ipv6 urls should use it...

**Comment by marcussacana** [comment] 2022-01-16 23:45
Fixed with https://github.com/marcussacana/DirectPackageInstaller/commit/d76d78890bd6456880496df0f71135c1a84b396b

**Comment by shpyntov** [comment] 2022-01-17 07:32
Now with that my link after click "load" button it freezes and crushes.

**Comment by marcussacana** [comment] 2022-01-17 23:33
Dear god, that same link?

**Comment by marcussacana** [comment] 2022-01-20 00:24
Missing information

**Comment by shpyntov** [comment] 2022-01-25 13:54
i have VSCodium, but cant run app for debug(
how can i run it?

**Comment by marcussacana** [comment] 2022-01-25 14:37
VSCode you will need install C# extensions.
The correct way is use the visual studio by the way

**Comment by shpyntov** [comment] 2022-01-25 14:41
dm me https://t.me/shpyntov

**Comment by marcussacana** [comment] 2022-01-25 14:55
Discord: Marcus André#0956

**Comment by marcussacana** [comment] 2022-01-25 15:02
by the way, you sould give a try in this one, they should create a log file in the directory.
[DPI Debug.rar.zip](https://github.com/marcussacana/DirectPackageInstaller/files/7934596/DPI.Debug.rar.zip)
o

**Comment by shpyntov** [comment] 2022-01-25 15:09
`http://185.17.121.131/It%20Takes%20Two%20[5.05%20Fix]/EP0006-CUSA16746_00-NUTSEU0000000000-A0102-V0100-CyB1K.pkg`

**Comment by marcussacana** [comment] 2022-01-25 15:18
Fine, you can close the server now.
The problem isn't with the DPI itself but your server software don't handle the url escape well.
That said is possible to fix in my side that, I will upload a new build soon

**Comment by marcussacana** [comment] 2022-01-25 15:29
Fixed, take a look.
if works then close the issue.

**Comment by marcussacana** [comment] 2022-01-29 22:00
Fixed in newest build

**Closed by marcussacana** 2022-01-29 22:00 UTC
